version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./resources:/docker-entrypoint-initdb.d
      - ./data_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass